### ISSUE TITLE
Déploiement continu des formations

### ISSUE THREAD

**Issue by hgwood** [Zenika/zenika-formation-framework#140]
# Definition of Done

- [X] Chaque push sur master déploie les slides sur AppEngine pour consultation par Zenika.
- [ ] Chaque push sur master déploie le cahier d'exercices sur AppEngine pour consultation par Zenika.
- [x] Chaque push sur master déploie le PDF les slides sur AppEngine pour accès par les formateurs (au cas où les participants ne l'aurait pas reçu).
  - bloqué par #128
- [X] Chaque push sur master déploie le PDF du cahier d'exercice sur AppEngine pour accès par les formateurs (au cas où les participants ne l'aurait pas reçu).
- [x] #110 Chaque push sur master dépose le PDF des slides et le PDF du cahier d'exercice sur Google Drive pour être disponibles à Training pour l'envoi aux participants
- [x] #98 Les PDF générés sont traçable jusqu'à une version du code (par exemple via SHA1, et date pour les non-techniques).

# Idées supplémentaires

- [X] #146 Un seul projet AppEngine pour toutes les formations plutôt que un par formation.
- [X] #35 Changer la police du PDF des cahiers d'exercices
- #96 Eviter les erreurs de concaténations quand il manque une ligne blanche en fin de fichier Markdown qui décrit un morceau d'un cahier d'exercice.
- ~~#97~~ Déployer un ZIP sur AppEngine qui contient les pages HTML des slides et du cahier d'exercice, ainsi que les PDF.
- #100 Déployer un ZIP qui contient les outils de travail nécessaires pour les participants.
- #65 Déployer toutes les branches.
- Notifier quand une nouvelle version est disponible. Questions : qui et par quel canal ? Les consultants sur Slack et/ou Workplace ? Le public sur Twitter ?

**Comment by hgwood** [comment]
There is only one item remaining: "Chaque push sur master déploie le cahier d'exercices sur AppEngine pour consultation par Zenika." I'm going to ignore it because it has very little value. Closing.
