### ISSUE TITLE
Replace PhantomJS by Headless Chrome

### ISSUE THREAD

**Issue by hgwood** [Zenika/zenika-formation-framework#185]
Supersedes #168.

Chrome 59 will support headless mode with pdf printing.

See branch `path-to-headless-chrome` and #187.

Questions & answers:
- should we require Chrome to be installed on the host or should we use a docker image?
  - both
- can CircleCI handle a docker run in the build? 
  - yes, but turns out no need (thanks to puppeteer)
- should we build a custom image?
 - no (thanks to puppeteer)
Progress:
- [X] Migrate PDF generation for slides to Chrome (#192)
- [X] Refactor to use ~~Chrome Launcher (see [here](https://github.com/Zenika/zenika-formation-framework/pull/187#issuecomment-308201459))~~ [Puppeteer](https://github.com/GoogleChrome/puppeteer) (#201)
- [X] Build a new Docker image that is capable of generating the PDFs with Headless Chrome (#201)

PDF generation for slides is done (#187). Need to do the same for labs.

- [X] Replace PhantomJS by Chrome for labs PDF printing (#202)

**Comment by jlandure** [comment]
We could use both: host install and docker image.
For CircleCI, it supports a docker run. We could use the official image if exists or build our own image with all the dependencies.
Sample circle.yml with `docker run` commands: https://github.com/Zenika/POC_EasyToGo/blob/master/circle.yml

**Comment by hgwood** [comment]
Progress today:
- [this docker image](https://store.docker.com/community/images/yukinying/chrome-headless-browser) works well; pdf printing requires `--entrypoint` (see second example [here](https://github.com/yukinying/chrome-headless-browser-docker#how-to-run-the-container))
- when pointed to the html slides, the pdf only has a white page with the "back-to-top" arrow in the lower left corner, because the slides are not loaded yet (this is async)
- to have the slides displayed in the pdf, a script like [this one]() must be written for headless chrome
- this script can use [`chrome-remote-interface`](https://www.npmjs.com/package/chrome-remote-interface) like shown [here](https://developers.google.com/web/updates/2017/04/headless-chrome#useprotocol)
- but pdf printing requires remote debugger to be disabled? there is an error message if `--print-pdf --remote-debugging-port=...` are specified
- so how to drive the browser?

need to investigate more:
- will pdf printing and remote debugger be able to both work at the same time in near future release?
- could we pre-render slides instead so that no JS is involved and no driving would be required

**Comment by hgwood** [comment]
According to [this](https://bugs.chromium.org/p/chromium/issues/detail?id=603559#c46), PDF printing can be triggered via the remote interface without `--print-pdf` being there, and that's actually the preferred method.

**Comment by hgwood** [comment]
PR: #192.
